checks:
    python:
        code_rating: true
        duplicate_code: true
tools:
    external_code_coverage:
        timeout: 600
        runs: 1
build:
    nodes:
        analysis:
            tests:
                override: [php-scrutinizer-run]
