package:
    name:           reppy
    type:           project
    headline:       rEPPy
    title:          Python EPP client and library
    keywords:       python, epp, client, library
    description:    |
        [EPP](https://en.wikipedia.org/wiki/Extensible_Provisioning_Protocol) is Extensible Provisioning Protocol.
        This package provides:
        - library for building EPP requests
        - EPP client implemented as a UNIX daemon
        - whole infrastructure for domain name registrar
        For the moment it is in early stage of development.

require:
    hiqdev/hidev-hiqdev: "*"
    hiqdev/hidev-python: "*"
