package:
    type:           project
    name:           reppy
    title:          EPP client and library in Python
    headline:       rEPPy
    keywords:       epp, client, library
    description:    |
        [EPP](https://en.wikipedia.org/wiki/Extensible_Provisioning_Protocol) is Extensible Provisioning Protocol used for registrar-registry communication to register and manage domains.

        This package provides:

        - library for building and parsing EPP requests and responses
        - EPP client implemented as a UNIX daemon
        - whole infrastructure for implementing domain name registrar

        For the moment it is in early stage of development.

require:
    hiqdev/hidev-python: "*@dev"
    hiqdev/hidev-pypi:   "*@dev"
    hiqdev/hidev-vendor: "*"
